spring.application.name=book-vault


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=solvative
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# H2 disabled in postgres profile
spring.h2.console.enabled=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.defer-datasource-initialization=true

# Run schema.sql and data.sql
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data-postgres.sql
spring.sql.init.continue-on-error=false

# JSON
spring.jackson.default-property-inclusion=non_null

# JWT
app.jwt.secret=bookvault-super-secret-jwt-signing-key-must-be-at-least-32-chars
app.jwt.expiration-ms=86400000

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.solvative.book_vault=INFO

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html