spring.application.name=book-vault


spring.profile.active=postgre

spring.datasource.url=jdbc:h2:mem:bookvault;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.defer-datasource-initialization=false

# default Data
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=false

# JSON
spring.jackson.default-property-inclusion=non_null

# JWT
app.jwt.secret=bookvault-super-secret-jwt-signing-key-must-be-at-least-32-chars
app.jwt.expiration-ms=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.solvative.book_vault=DEBUG

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html