DROP TABLE IF EXISTS Loans;
DROP TABLE IF EXISTS Auth_users;
DROP TABLE IF EXISTS Members;
DROP TABLE IF EXISTS Books;

CREATE TABLE Books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(17) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    genre VARCHAR(255),
    total_copies INT NOT NULL,
    available_copies INT NOT NULL,
    version BIGINT
);

CREATE TABLE Members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    membership_status VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP NOT NULL
);

CREATE TABLE Loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    borrowed_at TIMESTAMP NOT NULL,
    due_date TIMESTAMP NOT NULL,
    returned_at TIMESTAMP NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_loans_book
        FOREIGN KEY (book_id) REFERENCES books(id),
    CONSTRAINT fk_loans_member
        FOREIGN KEY (member_id) REFERENCES members(id)
);

-- Keep this only if your JWT/login flow uses an auth_users table.
CREATE TABLE Auth_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    member_id BIGINT NULL,
    CONSTRAINT fk_auth_users_member
        FOREIGN KEY (member_id) REFERENCES members(id)
);

CREATE INDEX idx_books_author ON Books(author);
CREATE INDEX idx_books_genre ON Books(genre);
CREATE INDEX idx_members_name ON Members(name);
CREATE INDEX idx_members_email ON Members(email);
CREATE INDEX idx_loans_book_id ON Loans(book_id);
CREATE INDEX idx_loans_member_id ON Loans(member_id);
CREATE INDEX idx_loans_due_date_status ON Loans(due_date, status);
CREATE INDEX idx_auth_users_username ON Auth_users(username);